/**
 * Validates that a value is a valid language Unicode language identifier (e.g. fr or zh-Hant).
 *
 * @author Alexey Bob <alexey.bob@gmail.com>
 */
'use strict';

import Validator from './ValidatorAbstract';

export default class extends Validator {
    constructor({
        message = null
    }) {
        super(arguments);

        this.configuring();

        this.setMessage('message', message);
    }

    configuring() {
        this.setDefaultMessages({
            'message': 'This value is not a valid language.'
        });

        this.initializeData();
    }

    validate(data) {
        this.resetErrors();

        if(!(data.toLowerCase() in this.languages)){
            this.addError(this.getMessage('message'));
        }
    }

    initializeData() {
        // Unicode language identifier
        this.languages = {
            'ab': 'Abkhazian',
            'ace': 'Achinese',
            'ach': 'Acoli',
            'ada': 'Adangme',
            'ady': 'Adyghe',
            'aa': 'Afar',
            'afh': 'Afrihili',
            'af': 'Afrikaans',
            'agq': 'Aghem',
            'ain': 'Ainu',
            'ak': 'Akan',
            'akk': 'Akkadian',
            'bss': 'Akoose',
            'akz': 'Alabama',
            'sq': 'Albanian',
            'ale': 'Aleut',
            'arq': 'Algerian Arabic',
            'en_us': 'American English',
            'ase': 'American Sign Language',
            'am': 'Amharic',
            'egy': 'Ancient Egyptian',
            'grc': 'Ancient Greek',
            'anp': 'Angika',
            'njo': 'Ao Naga',
            'ar': 'Arabic',
            'an': 'Aragonese',
            'arc': 'Aramaic',
            'aro': 'Araona',
            'arp': 'Arapaho',
            'arw': 'Arawak',
            'hy': 'Armenian',
            'rup': 'Aromanian',
            'frp': 'Arpitan',
            'as': 'Assamese',
            'ast': 'Asturian',
            'asa': 'Asu',
            'cch': 'Atsam',
            'en_au': 'Australian English',
            'de_at': 'Austrian German',
            'av': 'Avaric',
            'ae': 'Avestan',
            'awa': 'Awadhi',
            'ay': 'Aymara',
            'az': 'Azerbaijani',
            'bfq': 'Badaga',
            'ksf': 'Bafia',
            'bfd': 'Bafut',
            'bqi': 'Bakhtiari',
            'ban': 'Balinese',
            'bal': 'Baluchi',
            'bm': 'Bambara',
            'bax': 'Bamun',
            'bjn': 'Banjar',
            'bas': 'Basaa',
            'ba': 'Bashkir',
            'eu': 'Basque',
            'bbc': 'Batak Toba',
            'bar': 'Bavarian',
            'bej': 'Beja',
            'be': 'Belarusian',
            'bem': 'Bemba',
            'bez': 'Bena',
            'bn': 'Bengali',
            'bew': 'Betawi',
            'bho': 'Bhojpuri',
            'bik': 'Bikol',
            'bin': 'Bini',
            'bpy': 'Bishnupriya',
            'bi': 'Bislama',
            'byn': 'Blin',
            'zbl': 'Blissymbols',
            'brx': 'Bodo',
            'bs': 'Bosnian',
            'brh': 'Brahui',
            'bra': 'Braj',
            'pt_br': 'Brazilian Portuguese',
            'br': 'Breton',
            'en_gb': 'British English',
            'bug': 'Buginese',
            'bg': 'Bulgarian',
            'bum': 'Bulu',
            'bua': 'Buriat',
            'my': 'Burmese',
            'cad': 'Caddo',
            'frc': 'Cajun French',
            'en_ca': 'Canadian English',
            'fr_ca': 'Canadian French',
            'yue': 'Cantonese',
            'cps': 'Capiznon',
            'car': 'Carib',
            'ca': 'Catalan',
            'cay': 'Cayuga',
            'ceb': 'Cebuano',
            'tzm': 'Central Atlas Tamazight',
            'dtp': 'Central Dusun',
            'ckb': 'Central Kurdish',
            'esu': 'Central Yupik',
            'shu': 'Chadian Arabic',
            'chg': 'Chagatai',
            'ch': 'Chamorro',
            'ce': 'Chechen',
            'chr': 'Cherokee',
            'chy': 'Cheyenne',
            'chb': 'Chibcha',
            'cgg': 'Chiga',
            'qug': 'Chimborazo Highland Quichua',
            'zh': 'Chinese',
            'chn': 'Chinook Jargon',
            'chp': 'Chipewyan',
            'cho': 'Choctaw',
            'cu': 'Church Slavic',
            'chk': 'Chuukese',
            'cv': 'Chuvash',
            'nwc': 'Classical Newari',
            'syc': 'Classical Syriac',
            'ksh': 'Colognian',
            'swb': 'Comorian',
            'swc': 'Congo Swahili',
            'cop': 'Coptic',
            'kw': 'Cornish',
            'co': 'Corsican',
            'cr': 'Cree',
            'mus': 'Creek',
            'crh': 'Crimean Turkish',
            'hr': 'Croatian',
            'cs': 'Czech',
            'dak': 'Dakota',
            'da': 'Danish',
            'dar': 'Dargwa',
            'dzg': 'Dazaga',
            'del': 'Delaware',
            'din': 'Dinka',
            'dv': 'Divehi',
            'doi': 'Dogri',
            'dgr': 'Dogrib',
            'dua': 'Duala',
            'nl': 'Dutch',
            'dyu': 'Dyula',
            'dz': 'Dzongkha',
            'frs': 'Eastern Frisian',
            'efi': 'Efik',
            'arz': 'Egyptian Arabic',
            'eka': 'Ekajuk',
            'elx': 'Elamite',
            'ebu': 'Embu',
            'egl': 'Emilian',
            'en': 'English',
            'myv': 'Erzya',
            'eo': 'Esperanto',
            'et': 'Estonian',
            'pt_pt': 'European Portuguese',
            'es_es': 'European Spanish',
            'ee': 'Ewe',
            'ewo': 'Ewondo',
            'ext': 'Extremaduran',
            'fan': 'Fang',
            'fat': 'Fanti',
            'fo': 'Faroese',
            'hif': 'Fiji Hindi',
            'fj': 'Fijian',
            'fil': 'Filipino',
            'fi': 'Finnish',
            'nl_be': 'Flemish',
            'fon': 'Fon',
            'gur': 'Frafra',
            'fr': 'French',
            'fur': 'Friulian',
            'ff': 'Fulah',
            'gaa': 'Ga',
            'gag': 'Gagauz',
            'gl': 'Galician',
            'gan': 'Gan Chinese',
            'lg': 'Ganda',
            'gay': 'Gayo',
            'gba': 'Gbaya',
            'gez': 'Geez',
            'ka': 'Georgian',
            'de': 'German',
            'aln': 'Gheg Albanian',
            'bbj': 'Ghomala',
            'glk': 'Gilaki',
            'gil': 'Gilbertese',
            'gom': 'Goan Konkani',
            'gon': 'Gondi',
            'gor': 'Gorontalo',
            'got': 'Gothic',
            'grb': 'Grebo',
            'el': 'Greek',
            'gn': 'Guarani',
            'gu': 'Gujarati',
            'guz': 'Gusii',
            'gwi': 'Gwichʼin',
            'hai': 'Haida',
            'ht': 'Haitian',
            'hak': 'Hakka Chinese',
            'ha': 'Hausa',
            'haw': 'Hawaiian',
            'he': 'Hebrew',
            'hz': 'Herero',
            'hil': 'Hiligaynon',
            'hi': 'Hindi',
            'ho': 'Hiri Motu',
            'hit': 'Hittite',
            'hmn': 'Hmong',
            'hu': 'Hungarian',
            'hup': 'Hupa',
            'iba': 'Iban',
            'ibb': 'Ibibio',
            'is': 'Icelandic',
            'io': 'Ido',
            'ig': 'Igbo',
            'ilo': 'Iloko',
            'smn': 'Inari Sami',
            'id': 'Indonesian',
            'izh': 'Ingrian',
            'inh': 'Ingush',
            'ia': 'Interlingua',
            'ie': 'Interlingue',
            'iu': 'Inuktitut',
            'ik': 'Inupiaq',
            'ga': 'Irish',
            'it': 'Italian',
            'jam': 'Jamaican Creole English',
            'ja': 'Japanese',
            'jv': 'Javanese',
            'kaj': 'Jju',
            'dyo': 'Jola-Fonyi',
            'jrb': 'Judeo-Arabic',
            'jpr': 'Judeo-Persian',
            'jut': 'Jutish',
            'kbd': 'Kabardian',
            'kea': 'Kabuverdianu',
            'kab': 'Kabyle',
            'kac': 'Kachin',
            'kgp': 'Kaingang',
            'kkj': 'Kako',
            'kl': 'Kalaallisut',
            'kln': 'Kalenjin',
            'xal': 'Kalmyk',
            'kam': 'Kamba',
            'kbl': 'Kanembu',
            'kn': 'Kannada',
            'kr': 'Kanuri',
            'kaa': 'Kara-Kalpak',
            'krc': 'Karachay-Balkar',
            'krl': 'Karelian',
            'ks': 'Kashmiri',
            'csb': 'Kashubian',
            'kaw': 'Kawi',
            'kk': 'Kazakh',
            'ken': 'Kenyang',
            'kha': 'Khasi',
            'km': 'Khmer',
            'kho': 'Khotanese',
            'khw': 'Khowar',
            'ki': 'Kikuyu',
            'kmb': 'Kimbundu',
            'krj': 'Kinaray-a',
            'rw': 'Kinyarwanda',
            'kiu': 'Kirmanjki',
            'tlh': 'Klingon',
            'bkm': 'Kom',
            'kv': 'Komi',
            'koi': 'Komi-Permyak',
            'kg': 'Kongo',
            'kok': 'Konkani',
            'ko': 'Korean',
            'kfo': 'Koro',
            'kos': 'Kosraean',
            'avk': 'Kotava',
            'khq': 'Koyra Chiini',
            'ses': 'Koyraboro Senni',
            'kpe': 'Kpelle',
            'kri': 'Krio',
            'kj': 'Kuanyama',
            'kum': 'Kumyk',
            'ku': 'Kurdish',
            'kru': 'Kurukh',
            'kut': 'Kutenai',
            'nmg': 'Kwasio',
            'ky': 'Kyrgyz',
            'quc': 'Kʼicheʼ',
            'lad': 'Ladino',
            'lah': 'Lahnda',
            'lkt': 'Lakota',
            'lam': 'Lamba',
            'lag': 'Langi',
            'lo': 'Lao',
            'ltg': 'Latgalian',
            'la': 'Latin',
            'es_419': 'Latin American Spanish',
            'lv': 'Latvian',
            'lzz': 'Laz',
            'lez': 'Lezghian',
            'lij': 'Ligurian',
            'li': 'Limburgish',
            'ln': 'Lingala',
            'lfn': 'Lingua Franca Nova',
            'lzh': 'Literary Chinese',
            'lt': 'Lithuanian',
            'liv': 'Livonian',
            'jbo': 'Lojban',
            'lmo': 'Lombard',
            'nds': 'Low German',
            'sli': 'Lower Silesian',
            'dsb': 'Lower Sorbian',
            'loz': 'Lozi',
            'lu': 'Luba-Katanga',
            'lua': 'Luba-Lulua',
            'lui': 'Luiseno',
            'smj': 'Lule Sami',
            'lun': 'Lunda',
            'luo': 'Luo',
            'lb': 'Luxembourgish',
            'luy': 'Luyia',
            'mde': 'Maba',
            'mk': 'Macedonian',
            'jmc': 'Machame',
            'mad': 'Madurese',
            'maf': 'Mafa',
            'mag': 'Magahi',
            'vmf': 'Main-Franconian',
            'mai': 'Maithili',
            'mak': 'Makasar',
            'mgh': 'Makhuwa-Meetto',
            'kde': 'Makonde',
            'mg': 'Malagasy',
            'ms': 'Malay',
            'ml': 'Malayalam',
            'mt': 'Maltese',
            'mnc': 'Manchu',
            'mdr': 'Mandar',
            'man': 'Mandingo',
            'mni': 'Manipuri',
            'gv': 'Manx',
            'mi': 'Maori',
            'arn': 'Mapuche',
            'mr': 'Marathi',
            'chm': 'Mari',
            'mh': 'Marshallese',
            'mwr': 'Marwari',
            'mas': 'Masai',
            'mzn': 'Mazanderani',
            'byv': 'Medumba',
            'men': 'Mende',
            'mwv': 'Mentawai',
            'mer': 'Meru',
            'mgo': 'Metaʼ',
            'es_mx': 'Mexican Spanish',
            'mic': 'Micmac',
            'dum': 'Middle Dutch',
            'enm': 'Middle English',
            'frm': 'Middle French',
            'gmh': 'Middle High German',
            'mga': 'Middle Irish',
            'nan': 'Min Nan Chinese',
            'min': 'Minangkabau',
            'xmf': 'Mingrelian',
            'mwl': 'Mirandese',
            'lus': 'Mizo',
            'ar_001': 'Modern Standard Arabic',
            'moh': 'Mohawk',
            'mdf': 'Moksha',
            'ro_md': 'Moldavian',
            'lol': 'Mongo',
            'mn': 'Mongolian',
            'mfe': 'Morisyen',
            'ary': 'Moroccan Arabic',
            'mos': 'Mossi',
            'mul': 'Multiple Languages',
            'mua': 'Mundang',
            'ttt': 'Muslim Tat',
            'mye': 'Myene',
            'naq': 'Nama',
            'na': 'Nauru',
            'nv': 'Navajo',
            'ng': 'Ndonga',
            'nap': 'Neapolitan',
            'ne': 'Nepali',
            'new': 'Newari',
            'sba': 'Ngambay',
            'nnh': 'Ngiemboon',
            'jgo': 'Ngomba',
            'yrl': 'Nheengatu',
            'nia': 'Nias',
            'niu': 'Niuean',
            'zxx': 'No linguistic content',
            'nog': 'Nogai',
            'nd': 'North Ndebele',
            'frr': 'Northern Frisian',
            'se': 'Northern Sami',
            'nso': 'Northern Sotho',
            'no': 'Norwegian',
            'nb': 'Norwegian Bokmål',
            'nn': 'Norwegian Nynorsk',
            'nov': 'Novial',
            'nus': 'Nuer',
            'nym': 'Nyamwezi',
            'ny': 'Nyanja',
            'nyn': 'Nyankole',
            'tog': 'Nyasa Tonga',
            'nyo': 'Nyoro',
            'nzi': 'Nzima',
            'nqo': 'NʼKo',
            'oc': 'Occitan',
            'oj': 'Ojibwa',
            'ang': 'Old English',
            'fro': 'Old French',
            'goh': 'Old High German',
            'sga': 'Old Irish',
            'non': 'Old Norse',
            'peo': 'Old Persian',
            'pro': 'Old Provençal',
            'or': 'Oriya',
            'om': 'Oromo',
            'osa': 'Osage',
            'os': 'Ossetic',
            'ota': 'Ottoman Turkish',
            'pal': 'Pahlavi',
            'pfl': 'Palatine German',
            'pau': 'Palauan',
            'pi': 'Pali',
            'pam': 'Pampanga',
            'pag': 'Pangasinan',
            'pap': 'Papiamento',
            'ps': 'Pashto',
            'pdc': 'Pennsylvania German',
            'fa': 'Persian',
            'phn': 'Phoenician',
            'pcd': 'Picard',
            'pms': 'Piedmontese',
            'pdt': 'Plautdietsch',
            'pon': 'Pohnpeian',
            'pl': 'Polish',
            'pnt': 'Pontic',
            'pt': 'Portuguese',
            'prg': 'Prussian',
            'pa': 'Punjabi',
            'qu': 'Quechua',
            'raj': 'Rajasthani',
            'rap': 'Rapanui',
            'rar': 'Rarotongan',
            'rif': 'Riffian',
            'rgn': 'Romagnol',
            'ro': 'Romanian',
            'rm': 'Romansh',
            'rom': 'Romany',
            'rof': 'Rombo',
            'root': 'Root',
            'rtm': 'Rotuman',
            'rug': 'Roviana',
            'rn': 'Rundi',
            'ru': 'Russian',
            'rue': 'Rusyn',
            'rwk': 'Rwa',
            'ssy': 'Saho',
            'sah': 'Sakha',
            'sam': 'Samaritan Aramaic',
            'saq': 'Samburu',
            'sm': 'Samoan',
            'sgs': 'Samogitian',
            'sad': 'Sandawe',
            'sg': 'Sango',
            'sbp': 'Sangu',
            'sa': 'Sanskrit',
            'sat': 'Santali',
            'sc': 'Sardinian',
            'sas': 'Sasak',
            'sdc': 'Sassarese Sardinian',
            'stq': 'Saterland Frisian',
            'saz': 'Saurashtra',
            'sco': 'Scots',
            'gd': 'Scottish Gaelic',
            'sly': 'Selayar',
            'sel': 'Selkup',
            'seh': 'Sena',
            'see': 'Seneca',
            'sr': 'Serbian',
            'sh': 'Serbo-Croatian',
            'srr': 'Serer',
            'sei': 'Seri',
            'ksb': 'Shambala',
            'shn': 'Shan',
            'sn': 'Shona',
            'ii': 'Sichuan Yi',
            'scn': 'Sicilian',
            'sid': 'Sidamo',
            'bla': 'Siksika',
            'szl': 'Silesian',
            'zh_hans': 'Simplified Chinese',
            'sd': 'Sindhi',
            'si': 'Sinhala',
            'sms': 'Skolt Sami',
            'den': 'Slave',
            'sk': 'Slovak',
            'sl': 'Slovenian',
            'xog': 'Soga',
            'sog': 'Sogdien',
            'so': 'Somali',
            'snk': 'Soninke',
            'azb': 'South Azerbaijani',
            'nr': 'South Ndebele',
            'alt': 'Southern Altai',
            'sma': 'Southern Sami',
            'st': 'Southern Sotho',
            'es': 'Spanish',
            'srn': 'Sranan Tongo',
            'zgh': 'Standard Moroccan Tamazight',
            'suk': 'Sukuma',
            'sux': 'Sumerian',
            'su': 'Sundanese',
            'sus': 'Susu',
            'sw': 'Swahili',
            'ss': 'Swati',
            'sv': 'Swedish',
            'fr_ch': 'Swiss French',
            'gsw': 'Swiss German',
            'de_ch': 'Swiss High German',
            'syr': 'Syriac',
            'shi': 'Tachelhit',
            'tl': 'Tagalog',
            'ty': 'Tahitian',
            'dav': 'Taita',
            'tg': 'Tajik',
            'tly': 'Talysh',
            'tmh': 'Tamashek',
            'ta': 'Tamil',
            'trv': 'Taroko',
            'twq': 'Tasawaq',
            'tt': 'Tatar',
            'te': 'Telugu',
            'ter': 'Tereno',
            'teo': 'Teso',
            'tet': 'Tetum',
            'th': 'Thai',
            'bo': 'Tibetan',
            'tig': 'Tigre',
            'ti': 'Tigrinya',
            'tem': 'Timne',
            'tiv': 'Tiv',
            'tli': 'Tlingit',
            'tpi': 'Tok Pisin',
            'tkl': 'Tokelau',
            'to': 'Tongan',
            'fit': 'Tornedalen Finnish',
            'zh_hant': 'Traditional Chinese',
            'tkr': 'Tsakhur',
            'tsd': 'Tsakonian',
            'tsi': 'Tsimshian',
            'ts': 'Tsonga',
            'tn': 'Tswana',
            'tcy': 'Tulu',
            'tum': 'Tumbuka',
            'aeb': 'Tunisian Arabic',
            'tr': 'Turkish',
            'tk': 'Turkmen',
            'tru': 'Turoyo',
            'tvl': 'Tuvalu',
            'tyv': 'Tuvinian',
            'tw': 'Twi',
            'kcg': 'Tyap',
            'udm': 'Udmurt',
            'uga': 'Ugaritic',
            'uk': 'Ukrainian',
            'umb': 'Umbundu',
            'und': 'Unknown Language',
            'hsb': 'Upper Sorbian',
            'ur': 'Urdu',
            'ug': 'Uyghur',
            'uz': 'Uzbek',
            'vai': 'Vai',
            've': 'Venda',
            'vec': 'Venetian',
            'vep': 'Veps',
            'vi': 'Vietnamese',
            'vo': 'Volapük',
            'vot': 'Votic',
            'vun': 'Vunjo',
            'vro': 'Võro',
            'wa': 'Walloon',
            'wae': 'Walser',
            'war': 'Waray',
            'wbp': 'Warlpiri',
            'was': 'Washo',
            'guc': 'Wayuu',
            'cy': 'Welsh',
            'vls': 'West Flemish',
            'fy': 'Western Frisian',
            'mrj': 'Western Mari',
            'wal': 'Wolaytta',
            'wo': 'Wolof',
            'wuu': 'Wu Chinese',
            'xh': 'Xhosa',
            'hsn': 'Xiang Chinese',
            'yav': 'Yangben',
            'yao': 'Yao',
            'yap': 'Yapese',
            'ybb': 'Yemba',
            'yi': 'Yiddish',
            'yo': 'Yoruba',
            'zap': 'Zapotec',
            'dje': 'Zarma',
            'zza': 'Zaza',
            'zea': 'Zeelandic',
            'zen': 'Zenaga',
            'za': 'Zhuang',
            'gbz': 'Zoroastrian Dari',
            'zu': 'Zulu',
            'zun': 'Zuni'
        };

//        this.languages = {
//            'af': 'Afrikaans',
//            'af-ZA': 'Afrikaans (South Africa)',
//            'ar': 'Arabic',
//            'ar-AE': 'Arabic (U.A.E.)',
//            'ar-BH': 'Arabic (Bahrain)',
//            'ar-DZ': 'Arabic (Algeria)',
//            'ar-EG': 'Arabic (Egypt)',
//            'ar-IQ': 'Arabic (Iraq)',
//            'ar-JO': 'Arabic (Jordan)',
//            'ar-KW': 'Arabic (Kuwait)',
//            'ar-LB': 'Arabic (Lebanon)',
//            'ar-LY': 'Arabic (Libya)',
//            'ar-MA': 'Arabic (Morocco)',
//            'ar-OM': 'Arabic (Oman)',
//            'ar-QA': 'Arabic (Qatar)',
//            'ar-SA': 'Arabic (Saudi Arabia)',
//            'ar-SY': 'Arabic (Syria)',
//            'ar-TN': 'Arabic (Tunisia)',
//            'ar-YE': 'Arabic (Yemen)',
//            'az': 'Azeri (Latin)',
//            'az-AZ': 'Azeri (Latin) (Azerbaijan)',
//            'az-AZ': 'Azeri (Cyrillic) (Azerbaijan)',
//            'be': 'Belarusian',
//            'be-BY': 'Belarusian (Belarus)',
//            'bg': 'Bulgarian',
//            'bg-BG': 'Bulgarian (Bulgaria)',
//            'bs-BA': 'Bosnian (Bosnia and Herzegovina)',
//            'ca': 'Catalan',
//            'ca-ES': 'Catalan (Spain)',
//            'cs': 'Czech',
//            'cs-CZ': 'Czech (Czech Republic)',
//            'cy': 'Welsh',
//            'cy-GB': 'Welsh (United Kingdom)',
//            'da': 'Danish',
//            'da-DK': 'Danish (Denmark)',
//            'de': 'German',
//            'de-AT': 'German (Austria)',
//            'de-CH': 'German (Switzerland)',
//            'de-DE': 'German (Germany)',
//            'de-LI': 'German (Liechtenstein)',
//            'de-LU': 'German (Luxembourg)',
//            'dv': 'Divehi',
//            'dv-MV': 'Divehi (Maldives)',
//            'el': 'Greek',
//            'el-GR': 'Greek (Greece)',
//            'en': 'English',
//            'en-AU': 'English (Australia)',
//            'en-BZ': 'English (Belize)',
//            'en-CA': 'English (Canada)',
//            'en-CB': 'English (Caribbean)',
//            'en-GB': 'English (United Kingdom)',
//            'en-IE': 'English (Ireland)',
//            'en-JM': 'English (Jamaica)',
//            'en-NZ': 'English (New Zealand)',
//            'en-PH': 'English (Republic of the Philippines)',
//            'en-TT': 'English (Trinidad and Tobago)',
//            'en-US': 'English (United States)',
//            'en-ZA': 'English (South Africa)',
//            'en-ZW': 'English (Zimbabwe)',
//            'eo': 'Esperanto',
//            'es': 'Spanish',
//            'es-AR': 'Spanish (Argentina)',
//            'es-BO': 'Spanish (Bolivia)',
//            'es-CL': 'Spanish (Chile)',
//            'es-CO': 'Spanish (Colombia)',
//            'es-CR': 'Spanish (Costa Rica)',
//            'es-DO': 'Spanish (Dominican Republic)',
//            'es-EC': 'Spanish (Ecuador)',
//            'es-ES': 'Spanish (Castilian)',
//            'es-ES': 'Spanish (Spain)',
//            'es-GT': 'Spanish (Guatemala)',
//            'es-HN': 'Spanish (Honduras)',
//            'es-MX': 'Spanish (Mexico)',
//            'es-NI': 'Spanish (Nicaragua)',
//            'es-PA': 'Spanish (Panama)',
//            'es-PE': 'Spanish (Peru)',
//            'es-PR': 'Spanish (Puerto Rico)',
//            'es-PY': 'Spanish (Paraguay)',
//            'es-SV': 'Spanish (El Salvador)',
//            'es-UY': 'Spanish (Uruguay)',
//            'es-VE': 'Spanish (Venezuela)',
//            'et': 'Estonian',
//            'et-EE': 'Estonian (Estonia)',
//            'eu': 'Basque',
//            'eu-ES': 'Basque (Spain)',
//            'fa': 'Farsi',
//            'fa-IR': 'Farsi (Iran)',
//            'fi': 'Finnish',
//            'fi-FI': 'Finnish (Finland)',
//            'fo': 'Faroese',
//            'fo-FO': 'Faroese (Faroe Islands)',
//            'fr': 'French',
//            'fr-BE': 'French (Belgium)',
//            'fr-CA': 'French (Canada)',
//            'fr-CH': 'French (Switzerland)',
//            'fr-FR': 'French (France)',
//            'fr-LU': 'French (Luxembourg)',
//            'fr-MC': 'French (Principality of Monaco)',
//            'gl': 'Galician',
//            'gl-ES': 'Galician (Spain)',
//            'gu': 'Gujarati',
//            'gu-IN': 'Gujarati (India)',
//            'he': 'Hebrew',
//            'he-IL': 'Hebrew (Israel)',
//            'hi': 'Hindi',
//            'hi-IN': 'Hindi (India)',
//            'hr': 'Croatian',
//            'hr-BA': 'Croatian (Bosnia and Herzegovina)',
//            'hr-HR': 'Croatian (Croatia)',
//            'hu': 'Hungarian',
//            'hu-HU': 'Hungarian (Hungary)',
//            'hy': 'Armenian',
//            'hy-AM': 'Armenian (Armenia)',
//            'id': 'Indonesian',
//            'id-ID': 'Indonesian (Indonesia)',
//            'is': 'Icelandic',
//            'is-IS': 'Icelandic (Iceland)',
//            'it': 'Italian',
//            'it-CH': 'Italian (Switzerland)',
//            'it-IT': 'Italian (Italy)',
//            'ja': 'Japanese',
//            'ja-JP': 'Japanese (Japan)',
//            'ka': 'Georgian',
//            'ka-GE': 'Georgian (Georgia)',
//            'kk': 'Kazakh',
//            'kk-KZ': 'Kazakh (Kazakhstan)',
//            'kn': 'Kannada',
//            'kn-IN': 'Kannada (India)',
//            'ko': 'Korean',
//            'ko-KR': 'Korean (Korea)',
//            'kok': 'Konkani',
//            'kok-IN': 'Konkani (India)',
//            'ky': 'Kyrgyz',
//            'ky-KG': 'Kyrgyz (Kyrgyzstan)',
//            'lt': 'Lithuanian',
//            'lt-LT': 'Lithuanian (Lithuania)',
//            'lv': 'Latvian',
//            'lv-LV': 'Latvian (Latvia)',
//            'mi': 'Maori',
//            'mi-NZ': 'Maori (New Zealand)',
//            'mk': 'FYRO Macedonian',
//            'mk-MK': 'FYRO Macedonian (Former Yugoslav Republic of Macedonia)',
//            'mn': 'Mongolian',
//            'mn-MN': 'Mongolian (Mongolia)',
//            'mr': 'Marathi',
//            'mr-IN': 'Marathi (India)',
//            'ms': 'Malay',
//            'ms-BN': 'Malay (Brunei Darussalam)',
//            'ms-MY': 'Malay (Malaysia)',
//            'mt': 'Maltese',
//            'mt-MT': 'Maltese (Malta)',
//            'nb': 'Norwegian (Bokm?l)',
//            'nb-NO': 'Norwegian (Bokm?l) (Norway)',
//            'nl': 'Dutch',
//            'nl-BE': 'Dutch (Belgium)',
//            'nl-NL': 'Dutch (Netherlands)',
//            'nn-NO': 'Norwegian (Nynorsk) (Norway)',
//            'ns': 'Northern Sotho',
//            'ns-ZA': 'Northern Sotho (South Africa)',
//            'pa': 'Punjabi',
//            'pa-IN': 'Punjabi (India)',
//            'pl': 'Polish',
//            'pl-PL': 'Polish (Poland)',
//            'ps': 'Pashto',
//            'ps-AR': 'Pashto (Afghanistan)',
//            'pt': 'Portuguese',
//            'pt-BR': 'Portuguese (Brazil)',
//            'pt-PT': 'Portuguese (Portugal)',
//            'qu': 'Quechua',
//            'qu-BO': 'Quechua (Bolivia)',
//            'qu-EC': 'Quechua (Ecuador)',
//            'qu-PE': 'Quechua (Peru)',
//            'ro': 'Romanian',
//            'ro-RO': 'Romanian (Romania)',
//            'ru': 'Russian',
//            'ru-RU': 'Russian (Russia)',
//            'sa': 'Sanskrit',
//            'sa-IN': 'Sanskrit (India)',
//            'se': 'Sami (Northern)',
//            'se-FI': 'Sami (Northern) (Finland)',
//            'se-FI': 'Sami (Skolt) (Finland)',
//            'se-FI': 'Sami (Inari) (Finland)',
//            'se-NO': 'Sami (Northern) (Norway)',
//            'se-NO': 'Sami (Lule) (Norway)',
//            'se-NO': 'Sami (Southern) (Norway)',
//            'se-SE': 'Sami (Northern) (Sweden)',
//            'se-SE': 'Sami (Lule) (Sweden)',
//            'se-SE': 'Sami (Southern) (Sweden)',
//            'sk': 'Slovak',
//            'sk-SK': 'Slovak (Slovakia)',
//            'sl': 'Slovenian',
//            'sl-SI': 'Slovenian (Slovenia)',
//            'sq': 'Albanian',
//            'sq-AL': 'Albanian (Albania)',
//            'sr-BA': 'Serbian (Latin) (Bosnia and Herzegovina)',
//            'sr-BA': 'Serbian (Cyrillic) (Bosnia and Herzegovina)',
//            'sr-SP': 'Serbian (Latin) (Serbia and Montenegro)',
//            'sr-SP': 'Serbian (Cyrillic) (Serbia and Montenegro)',
//            'sv': 'Swedish',
//            'sv-FI': 'Swedish (Finland)',
//            'sv-SE': 'Swedish (Sweden)',
//            'sw': 'Swahili',
//            'sw-KE': 'Swahili (Kenya)',
//            'syr': 'Syriac',
//            'syr-SY': 'Syriac (Syria)',
//            'ta': 'Tamil',
//            'ta-IN': 'Tamil (India)',
//            'te': 'Telugu',
//            'te-IN': 'Telugu (India)',
//            'th': 'Thai',
//            'th-TH': 'Thai (Thailand)',
//            'tl': 'Tagalog',
//            'tl-PH': 'Tagalog (Philippines)',
//            'tn': 'Tswana',
//            'tn-ZA': 'Tswana (South Africa)',
//            'tr': 'Turkish',
//            'tr-TR': 'Turkish (Turkey)',
//            'tt': 'Tatar',
//            'tt-RU': 'Tatar (Russia)',
//            'ts': 'Tsonga',
//            'uk': 'Ukrainian',
//            'uk-UA': 'Ukrainian (Ukraine)',
//            'ur': 'Urdu',
//            'ur-PK': 'Urdu (Islamic Republic of Pakistan)',
//            'uz': 'Uzbek (Latin)',
//            'uz-UZ': 'Uzbek (Latin) (Uzbekistan)',
//            'uz-UZ': 'Uzbek (Cyrillic) (Uzbekistan)',
//            'vi': 'Vietnamese',
//            'vi-VN': 'Vietnamese (Viet Nam)',
//            'xh': 'Xhosa',
//            'xh-ZA': 'Xhosa (South Africa)',
//            'zh': 'Chinese',
//            'zh-CN': 'Chinese (S)',
//            'zh-HK': 'Chinese (Hong Kong)',
//            'zh-MO': 'Chinese (Macau)',
//            'zh-SG': 'Chinese (Singapore)',
//            'zh-TW': 'Chinese (T)',
//            'zu': 'Zulu',
//            'zu-ZA': 'Zulu (South Africa)'
//        };
    }
}
